# Generated by Django 5.2.5 on 2025-08-28 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_pending_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pending_email',
        ),
    ]
