# Generated by Django 5.2.5 on 2025-08-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='details',
            field=models.TextField(blank=True),
        ),
    ]
