# Generated by Django 5.2.5 on 2025-08-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='park_choice',
            field=models.CharField(choices=[('theme', 'Theme Park'), ('water', 'Water Park')], max_length=10),
        ),
    ]
