# Generated by Django 5.2.5 on 2025-08-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_alter_registration_park_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='is_gift',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
