# Generated by Django 5.2.5 on 2025-08-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_registration_is_gift_registration_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='is_gift',
        ),
        migrations.AddField(
            model_name='registration',
            name='gift_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
