# Generated by Django 5.2.5 on 2025-08-27 07:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_remove_registration_is_gift_registration_gift_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ['full_name']},
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='registration',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['trip', 'full_name'], name='trips_regis_trip_id_433172_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['status'], name='trips_regis_status_96389d_idx'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gte', 0)), name='trip_capacity_nonnegative'),
        ),
    ]
