# Generated by Django 5.2.5 on 2025-08-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_alter_registration_options_alter_trip_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='email_used',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
